spring:
  ai:
    openai:
      base-url: https://openrouter.ai/api
      api-key: ${OPENROUTER_API_KEY}
      chat:
        model: deepseek/deepseek-r1-0528-qwen3-8b:free

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/tabi/protocol/openid-connect/certs"

server:
  port: 8085