spring:
  ai:
    openai:
      base-url: https://openrouter.ai/api
      api-key: ${OPEN_ROUTER_API_KEY}
      chat:
        model: ${OPEN_ROUTER_LLM_MODEL}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/tabi/protocol/openid-connect/certs"

server:
  port: 8085