spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: travel-itinerary
        options:
          temperature: 0.7
          top-p: 0.9
          num-predict: 2048